<a href="https://colab.research.google.com/drive/1Hya1fDgRKdMJt-JJRmgCvR9ntp-nYE7W?usp=sharing" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание к 7 уроку.


**1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

TODO

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$



In [ ]:
import numpy as np

In [ ]:
A = np.array([
              [1,-2],
              [3,0]
              ])
B = np.array([
              [4,-1],
              [0,5]
              ])
print ('Сумма матриц А и В')
print(A + B)
print()
print ('Произведение матриц А и В')
print(A @ B)

Сумма матриц А и В
[[ 5 -3]
 [ 3  5]]

Произведение матриц А и В
[[  4 -11]
 [ 12  -3]]




---
Графическое решение

1)
$
\left(
\begin{array}{cccc}
{1} & {-2} \\
{3} & {0} 
\end{array}
\right) + \left(
\begin{array}{cccc}
{4} & {-1} \\
{0} & {5} 
\end{array}
\right) = \left(
\begin{array}{cccc}
{5} & {-3} \\
{3} & {5} 
\end{array}
\right)
$

2)
$\left(
\begin{array}{cccc}
{1} & {-2} \\
{3} & {0} 
\end{array}
\right) * \left(
\begin{array}{cccc}
{4} & {-1} \\
{0} & {5} 
\end{array}
\right) = \left(
\begin{array}{cccc}
{1*4 + (-2)*0} & {1*(-1) + (-2)*5} \\
{3*4 + 0*0} & {3*(-1) + 0*5} 
\end{array}
\right)=\left(
\begin{array}{cccc}
{4} & {-11} \\
{12} & {-3} 
\end{array}
\right) $


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$


In [ ]:
A = np.array([
              [1,7],
              [3,-6]
              ])
B = np.array([
              [0,5],
              [2,-1]
              ])
C = np.array([
              [2,-4],
              [1,1]
              ])
print('Результат выражения 3*A - 2*B + 4*C')
print(3*A - 2*B + 4*C)

Результат выражения 3*A - 2*B + 4*C
[[ 11  -5]
 [  9 -12]]



---
Графическое решение


$3A - 2B + 4C =
\begin{pmatrix}
3 & 21\\ 
9 & -18\\ 
\end{pmatrix}
$-$\begin{pmatrix}
0 & 10\\ 
4 & -2\\ 
\end{pmatrix}
$+$\begin{pmatrix}
8 & -16\\ 
4 & 4\\ 
\end{pmatrix}$=$\begin{pmatrix}
(3+0+8) & (21 - 10 -16)\\ 
(9-4-4) & (-18 + 2 + 4)\\ 
\end{pmatrix}$=$\begin{pmatrix}
11 & -5\\ 
9 & -12\\ 
\end{pmatrix}$


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


In [ ]:
A  = np.array([
               [4,1], 
               [5,-2], 
               [2,3]
               ])
AT = A.transpose()
print("A * AT")
print(np.dot(A, AT))
print()
print('AT * A')
print(AT @ A) 

A * AT
[[17 18 11]
 [18 29  4]
 [11  4 13]]

AT * A
[[45  0]
 [ 0 14]]



---
Графичское решение

$ AA^{T} = \left(
\begin{array}{cccc}
{4} & {1} \\
{5} & {-2} \\
{2} & {3}
\end{array}
\right) * \left(
\begin{array}{cccc}
{4} & {5} & {2}\\
{1} & {-2} & {3}
\end{array}
\right)= \left(
\begin{array}{cccc}
{4^2+1^2} & {4*5+1*-2} & {4*2+1*3} \\
{5*4-2*1} & {5^2-2^2} &{5*2+-2*3} \\
{2*4+3*1} & {2*5+3*-2} & {2^2+3^3}  
\end{array}
\right)= \left(
\begin{array}{cccc}
{17} & {18} & {11} \\
{18} & {29} &{4} \\
{11} & {4} & {31}  
\end{array}
\right)$


$
A^{T}A= \left(
\begin{array}{cccc}
{4} & {5} & {2}\\
{1} & {-2} & {3}
\end{array}
\right) *\left(
\begin{array}{cccc}
{4} & {1} \\
{5} & {-2} \\
{2} & {3}
\end{array}
\right)= \left(
\begin{array}{cccc}
{4^2+5^5+2^2} & {4*1+5*-2+2*3}\\
{1*4-2*5+3*2} & {1^1-2^2+3^2}
\end{array}
\right) = \left(
\begin{array}{cccc}
{45} & {0}\\
{0} & {14}
\end{array}
\right) $


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def matrix_multiply(m1, m2):
  r = []
  m = []
  for i in range(len(m1)):
      for j in range(len(m2[0])):
          sums = 0
          for k in range(len(m2)):
              sums = sums + (m1[i][k] * m2[k][j])
          r.append(sums)
      m.append(r)
      r = []
  return m 

In [ ]:
#Проверка
m1 = [[1, -2], [3, 0]]
m2 = [[4, -1], [0, 5]]
print(matrix_multiply(m1, m2))

[[4, -11], [12, -3]]



__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$





$ det = sinx * sinx -(-cosx) * cosx = 1 $ 

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    


$ det = (8*5*9) + (0*4*1) + (0*0*6) - (0*5*6) - (8*0*1) - ( 0*5*9) = 360$

   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$

$
det = (2*6*10) + (8*3*7) + (5*9*4)- (8*6*4) - (2*9*7) - (5*3*10) = 0
$


__7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   


 

---

---




а) $det(A^{2})= 4*4 =16$;
    
б) $det(A^{T})= 4$;
    
в) $det(2A)=8$.

__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



$ det = (-2 * -14 * 13) + 
(-3 * 7* 6) + 
(4 * 7 * -3) -
(-3 * -14 * -3) - 
(-2 * 7 * 6) - 
( 4 * 7 * 13)
= 0 
$

**Так как определитель матрицы = 0, значит матрица является вырожденной**

__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$


In [ ]:
a = np.array([
              [1, 2, 3],
              [1, 1, 1],
              [2, 3, 4]
              ])

rank_a = np.linalg.matrix_rank(a)

print(f'Ранг матрицы а) : {rank_a}')

Ранг матрицы а) : 2


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [ ]:
b = np.array([
              [0,0,2,1],
              [0,0,2,2],
              [0,0,4,3],
              [2,3,5,6]
              ])
rank_b = np.linalg.matrix_rank(b)
print(f'Ранг матрицы б) : {rank_b}')


Ранг матрицы б) : 3
